### ISSUE TITLE
Working environment

### ISSUE THREAD

**Issue by aplachy** [ortmann64/nfon#2]
Hello @ortmann64!

Since I'm not very familiar with node.js I have some troubles to get your code working for me.
Do you have some more examples or hints which requironments the code has?

With your examples I only get errors like this:
TypeError: Cannot read property 'version' of undefined

Thanks and best regards,
Andreas

**Comment by ortmann64** [comment]
Hey Andreas,

There was an issue with the module export in my package. I've fixed this now.
Please use the new version 1.0.2 - please let me know, if this works for you.

Thanks,
Sebastian

**Comment by aplachy** [comment]
Hey Sebastian!

Thanks for the quick response.
It seems to work now, but actually I'm still waiting for my keys, so I could not test all functions at the moment.

Thanks,
Andreas
