### ISSUE TITLE
access control check

### ISSUE THREAD

**Issue by faridrr** [ortmann64/nfon#3]
Hey @ortmann64 

I have an error while executing a localhost request ,I did not find  how integrate 'Access-Control-Allow-Origin' in the header
For that I must deactivate the security of my browser

![2021-04-12 15 01 03 localhost 9973867d9c6d](https://user-images.githubusercontent.com/33391553/114398463-1ab3dd80-9ba0-11eb-81fd-ca3d395f0956.jpg)

Thank you for this package

**Comment by ortmann64** [comment]
Hey @faridrr 

please show your code of your NodeJS server.

Thanks
